conda_build_tool: rattler-build
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
provider:
  osx_64: default
  osx_arm64: default
  linux_64: default
  linux_aarch64: default
workflow_settings:
  free_disk_space: max
